# Generated by Django 5.2.5 on 2025-08-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='history',
            field=models.TextField(default='[]'),
        ),
    ]
